import { Component, OnInit } from '@angular/core';
import postData from './data/posts.json';

@Component({
  selector: 'app-post-list',
  templateUrl: './post-list.component.html',
  styleUrls: ['./post-list.component.css'],
})
export class PostListComponent implements OnInit {
  private _maxShownItems = 5;

  private _startIndex = 0;

  private _nextIndex = 0;

  private _allPosts = postData;

  pageRange: Array<number> = [];

  featuredTitle = 'All Posts';

  curPage = 1;

  shownPosts = [];

  /** Adds number of pages to an array to display */
  private _setPagesRange() {
    for (let i = 1; i <= this._allPosts.length / this._maxShownItems; i++) {
      this.pageRange.push(i);
    }
  }

  /** Sets posts for the page */
  private _setPosts(startIdx: number, nextIdx: number): void {
    this.shownPosts = postData.slice(startIdx, nextIdx);
  }

  /** Sets the start and end range of posts to grab from the _allPosts array
   * @param start: starting index
   * @param end: ending index
   */
  private _setIndices(start: number, end: number) {
    this._startIndex = start;
    this._nextIndex = end;
  }

  /**
   * @param pageNum index from list item generated by *ngForOf
   */
  setCurPage(pageNum: number): void {
    this.curPage = pageNum;
    this._nextIndex = pageNum * this._maxShownItems;
    this._startIndex = this._nextIndex - this._maxShownItems;

    this._setPosts(this._startIndex, this._nextIndex);
  }

  setPageSelectorStyle(pageNum: number) {
    return this.curPage === pageNum ? 'page-number active' : 'page-number';
  }

  ngOnInit(): void {
    this._setPagesRange();

    this._setIndices(this._startIndex, this._maxShownItems);

    this._setPosts(this._startIndex, this._nextIndex);
  }
}
